version: "2"
services:
    Motel-main:
        container_name: Motel_main
        build: .
        environment:
            - NODE_ENV=development
            - LOG_LEVEL=debug
            - PORT=3000
            - DATABASE_CONNECTION=mysql
            - DATABASE_HOST=mysql
            - DATABASE_PORT=3306
            - DATABASE_USERNAME=dev
            - DATABASE_PASSWORD=dev
            - DATABASE_DB_NAME=main

        user: "1000:1000"
        volumes:
            - .:/app
        networks:
            - common

networks:
    common:
        external: true
